name: Daily Discord Message

on:
  schedule:
    - cron: "0 13 * * *"   # chạy lúc 20:00 giờ VN (13:00 UTC)
  workflow_dispatch:       # cho phép chạy thủ công để test

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python send.py
